#!/bin/bash

while true
do

# Logo

echo "============================================================"
curl -s https://raw.githubusercontent.com/AlekseyMoskalev1/script/main/Noders.sh | bash
echo "============================================================"


PS3='Select an action: '
options=("Prepare the server for installation" "Install GearNode" "Update node" "Log Node" "Delete node" "Exit")
select opt in "${options[@]}"
               do
                   case $opt in
"Update node")

wget https://builds.gear.rs/gear-nightly-linux-x86_64.tar.xz
sudo tar -xvf gear-nightly-linux-x86_64.tar.xz -C /root
rm gear-nightly-linux-x86_64.tar.xz
sudo systemctl restart gear-node

break
;;


"Delete node")

sudo systemctl stop gear-node
sudo systemctl disable gear-node
sudo rm -rf /root/.local/share/gear-node
sudo rm /etc/systemd/system/gear-node.service
sudo rm /root/gear-node

break
;;


"Prepare the server for installation")
               echo "============================================================"
               echo "Preparation has begun"
               echo "============================================================"
               
sudo apt update && sudo apt upgrade -y
sudo apt install -y git clang curl libssl-dev llvm libudev-dev

curl https://sh.rustup.rs -sSf | sh
source ~/.cargo/env

rustup default stable
rustup update
rustup update nightly
rustup target add wasm32-unknown-unknown --toolchain nightly



               echo "============================================================"
               echo "The server is ready!"
               echo "============================================================"
break
;;
            

"Install GearNode")
               echo "============================================================"
               echo "Installation started"
               echo "============================================================"
               echo "============================================================"
               echo "Your Node name:"
               echo "============================================================"
read GEARNODENAME
echo 'export GEARNODENAME='${GEARNODENAME} >> $HOME/.bash_profile
source ~/.bash_profile

wget https://builds.gear.rs/gear-nightly-linux-x86_64.tar.xz && \
tar xvf gear-nightly-linux-x86_64.tar.xz && \
rm gear-nightly-linux-x86_64.tar.xz && \
chmod +x $HOME/gear-node

sudo tee <<EOF >/dev/null /etc/systemd/system/gear-node.service
[Unit]
Description=Gear Node
After=network.target

[Service]
Type=simple
User=root
WorkingDirectory=/root/
ExecStart=/root/gear-node \
        --name $GEARNODENAME \
        --execution wasm \
        --log runtime \
        --telemetry-url 'ws://telemetry-backend-shard.gear-tech.io:32001/submit 0'
Restart=on-failure
RestartSec=3
LimitNOFILE=10000

[Install]
WantedBy=multi-user.target
EOF

echo "export GEARNODENAME="SeptimA[NODERS]"" >> ~/.bash_profile

sudo systemctl restart systemd-journald
sudo systemctl daemon-reload
sudo systemctl enable gear-node
sudo systemctl restart gear-node

break
;;

"Log Node")

sudo journalctl -n 100 -f -u gear-node

break
;;

"Exit")
exit
;;

*) echo "invalid option $REPLY";;
esac
done
done
